### ISSUE TITLE
ABNF for dns-scheme does not allow hostnames with ports

### ISSUE THREAD

**Issue by llorllale** [trustbloc/did-method-orb#1]
This is already a problem in [`did:web`](https://github.com/w3c-ccg/did-method-web/issues/7).

There is a note there indicating intent to have this scheme "more constrained than RFC3986" - I'd argue this is a mistake for the reasons pointed out in did:web.

I suggest importing the syntax for `reg-name` from RFC3986 as-is.

**Comment by troyronda** [comment]
The new `did:orb:hl` scheme supports embedded URLs.
