### ISSUE TITLE
"dns-scheme" is under-specified

### ISSUE THREAD

**Issue by llorllale** [trustbloc/did-method-orb#2]
Both `dns-scheme` and `dht-scheme` seem under-specified - but that's to be expected at this stage.

What catches my attention about the `dns-scheme` is that due to the ABNF there is no way to indicate the application-level protocol (URI _scheme_) used to interact with the entity possessing the content-addressed object. What application-level protocol should the resolver use to fetch the content-addressed object once they have an A record? HTTP? FTP? XMPP? `file://`?etc.

I suggest renaming this to `web-scheme`, change its value to `web`, and constrain its use to HTTPS. This aligns with the use of WebFinger.

The example given would change `dns` -> `web`:

```diff
- did:orb:dns:example.com:bafkreiatkubvbkdidscmqynkyls3iqawdqvthi7e6mbky2amuw3inxsi3y:EiDyOQbbZAa3aiRzeCkV7LOx3SERjjH93EXoIM3UoN4oWg
+ did:orb:web:example.com:bafkreiatkubvbkdidscmqynkyls3iqawdqvthi7e6mbky2amuw3inxsi3y:EiDyOQbbZAa3aiRzeCkV7LOx3SERjjH93EXoIM3UoN4oWg
```

**Comment by troyronda** [comment]
Correct - the intention is that the "dns" scheme results in a WebFinger query at the domain.

Yes - It might be better to use "web".

**Comment by troyronda** [comment]
Done.
